AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - "**/*.gemspec"
  TargetRubyVersion: 2.6

Style/FormatStringToken:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - "spec/**"

Layout/LineLength:
  Enabled: false
  Exclude:

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - _
    - k
    - v

