AllCops:
  DisplayCopNames: true
  Exclude:
    - "**/*.gemspec"
  TargetRubyVersion: 2.4

Style/FormatStringToken:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - "spec/**"

Metrics/LineLength:
  Enabled: false
  Exclude:

Lint/UselessComparison:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - _
    - k
    - v

