AllCops:
  DisplayCopNames: true
  Exclude:
    - "**/*.gemspec"
  TargetRubyVersion: 2.4

Metrics/LineLength:
  AllowURI: true
  Max: 120
  Exclude:
    - Gemfile*

Style/FormatStringToken:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - "spec/**"

Metrics/LineLength:
  Enabled: false
  Exclude:
    - "spec/**"

Lint/UselessComparison:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - _
    - k
    - v

